; feeds.ini

[Stormer]
uri = "https://dailystormer.in/feed/"

[HN]
uri = "https://hnrss.org/frontpage"

[HN Best Comments]
uri = "https://hnrss.org/bestcomments"

[Lobste.rs]
uri = "https://lobste.rs/rss"

[New York Times]
uri = "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"

[NPR]
uri = "https://www.npr.org/rss/rss.php"

[The Conversation]
uri = "https://theconversation.com/us/rss"

[The Intercept]
uri = "https://theintercept.com/feed/?rss"

[BBC]
uri = "http://feeds.bbci.co.uk/news/rss.xml"

[Quartz]
uri = "https://qz.com/feed/"

[PBS News Hour]
uri = "https://www.pbs.org/newshour/feeds/rss/headlines"

[Fox News]
uri = "http://feeds.foxnews.com/foxnews/latest"
