; feeds.ini

[HN]
uri = "https://hnrss.org/frontpage"

[HN Best Comments]
uri = "https://hnrss.org/bestcomments"

[Lobste.rs]
uri = "https://lobste.rs/rss"

[Chicago Tribune]
uri="https://www.chicagotribune.com/arcio/rss/"

[Zero Hedge]
uri = "https://cms.zerohedge.com/fullrss2.xml"

[News Max]
uri = "https://www.newsmax.com/rss/"

[The Atlantic]
uri = "https://www.theatlantic.com/feed/all/"

[Financial Times]
uri = "https://www.ft.com/rss/home/uk"

[Wall Street Journal (World News)]
uri = "https://feeds.a.dj.com/rss/RSSWorldNews.xml"

[Wall Street Journal (US Business)]
uri="https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml"

[The Daily Beast]
uri="https://feeds.thedailybeast.com/rss/articles"

[Business Insider]
uri="https://feeds.businessinsider.com/custom/all"

[The Smoking Gun]
uri="http://thesmokinggun.com/rss"

[New York Times]
uri = "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"

[NPR]
uri = "https://www.npr.org/rss/rss.php"

[The Conversation]
uri = "https://theconversation.com/us/rss"

[The Intercept]
uri = "https://theintercept.com/feed/?rss"

[BBC]
uri = "http://feeds.bbci.co.uk/news/rss.xml"

[Quartz]
uri = "https://qz.com/feed/"

[PBS News Hour]
uri = "https://www.pbs.org/newshour/feeds/rss/headlines"

[Fox News]
uri = "http://feeds.foxnews.com/foxnews/latest"
